config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :users, only: [:index, :show] do
    member do # work on specific instance of the user resource
      patch :resend_invitation #/users/:id/resend_invitation
    end
  end
  resources :tenants do
    get :user_tenants, on: :collection
    member do
      patch :switch #find the current tenant_id
    end
  end
  resources :members do
    get :invite, on: :collection
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :bigint
#  invitations_count      :integer          default(0)
#  tenant_id              :integer
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :invitable

  has_many :members, dependent: :destroy
  has_many :tenants, through: :members

  belongs_to :tenant, required: false

  def to_s
    email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ resend_invitation show ]

    def index
        @users = User.all
    end

    def resend_invitation
        if @user.invitation_accepted_at.present?
            redirect_to members_path, alert: "User has already accepted the invitation."
        else
            @user.invite! # unless @user.invitation_token.present?
            MemberInvitationMailer.resend_invitation_email(@user, current_user).deliver_later
            redirect_to members_path, notice: "Invitation resent successfully to #{@user.email}."
        end
    end

    def show
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/views/users/index.html.erb
<div class="container">
  <div class="box">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title is-4">Users</h1>
        </div>
        <div class="level-item">
          <span class="tag is-info is-light"><%= @users.count %> users</span>
        </div>
      </div>
    </div>

    <div class="table-container">
      <table class="table is-striped is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Tenants</th>
            <th>Created At</th>
            <th>Current Tenant Id</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.email %></td>
              <td><%= user.tenants.compact.join(', ') if user.tenants %></td>
              <td><%= user.created_at.strftime("%B %d, %Y") %></td>
              <td><b><%= user.tenant_id %></b></td>
              <td>
                <%= link_to user_path(user), class: "button is-small is-info" do %>
                  <span class="icon">
                    <i class="fas fa-eye"></i>
                  </span>
                  <span>View</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-centered">
    <div class="column is-8">
      <div class="box">
        <div class="level mb-5">
          <div class="level-left">
            <div class="level-item">
              <div class="icon-text">
                <span class="icon is-large">
                  <i class="fas fa-user-circle fa-3x"></i>
                </span>
              </div>
            </div>
            <div class="level-item">
              <div class="ml-4">
                <h1 class="title is-4 mb-2 has-text-break" style="max-width: 400px;"><%= @user.email %></h1>
              </div>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= link_to "Back to Users", users_path, class: "button is-light" %>
            </div>
          </div>
        </div>

        <hr class="mb-5">

        <div class="columns">
          <div class="column">
            <div class="box has-background-light">
              <h2 class="title is-5 mb-4">Account Information</h2>
              <div class="content">
                <table class="table is-fullwidth">
                  <tbody>
                    <tr>
                      <th style="width: 150px;">Email</th>
                      <td class="has-text-break" style="max-width: 400px;"><%= @user.email %></td>
                    </tr>
                    <tr>
                      <th>Created At</th>
                      <td><%= @user.created_at.strftime("%B %d, %Y at %I:%M %p") %></td>
                    </tr>
                    <tr>
                      <th>Last Updated</th>
                      <td><%= @user.updated_at.strftime("%B %d, %Y at %I:%M %p") %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <div class="columns mt-5">
          <div class="column">
            <% if current_user == @user %>
              <div class="buttons">
                <%= link_to edit_user_registration_path, class: "button is-primary" do %>
                  <span class="icon">
                    <i class="fas fa-edit"></i>
                  </span>
                  <span>Edit Profile</span>
                <% end %>
              </div>
            <% end %>
            <p class="has-text-grey mt-4">
              <span class="icon">
                <i class="fas fa-calendar-alt"></i>
              </span>
              Member since <%= @user.created_at.strftime("%B %d, %Y") %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>