config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :users, only: [:index, :show] do
    member do # work on specific instance of the user resource
      patch :resend_invitation #/users/:id/resend_invitation
    end
  end
  resources :tenants do
    get :user_tenants, on: :collection
    member do
      patch :switch #find the current tenant_id
    end
  end
  resources :members do
    get :invite, on: :collection
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <span class="icon-text">
        <span class="icon">
          <i class="fas fa-bolt"></i>
        </span>
        <span class="has-text-weight-bold">Rezz</span>
      </span>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasic" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <% if user_signed_in? %>
        <span class="navbar-item">
          <%=current_user.email.split('@').first%>:<%= current_tenant%>
        </span>
        <%= link_to "Users", users_path, class: "navbar-item" %>
        <%= link_to "Tenants", tenants_path, class: "navbar-item" %>
        <%= link_to "Members", members_path, class: "navbar-item" %>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <span class="icon-text">
                <span class="icon">
                  <i class="fas fa-user-circle"></i>
                </span>
                <span><%= current_user.email %></span>
              </span>
            </a>

            <div class="navbar-dropdown is-right">
              <div class="navbar-item">
                <div class="buttons is-fullwidth">
                  <%= link_to edit_user_registration_path, class: "button is-ghost is-small is-fullwidth has-text-black" do %>
                    <span class="icon-text">
                      <span class="icon has-text-black">
                        <i class="fas fa-user-edit"></i>
                      </span>
                      <span>Edit Profile</span>
                    </span>
                  <% end %>
                </div>
              </div>
              <hr class="navbar-divider">
              <div class="navbar-item">
                <div class="buttons is-fullwidth">
                  <%= button_to destroy_user_session_path, method: :delete, class: "button is-ghost is-small is-fullwidth has-text-black", form: { data: { turbo: true, turbo_confirm: "Are you sure you want to sign out?" } } do %>
                    <span class="icon-text">
                      <span class="icon has-text-black">
                        <i class="fas fa-sign-out-alt"></i>
                      </span>
                      <span>Sign Out</span>
                    </span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div class="buttons are-small">
            <%= link_to "Sign In", new_user_session_path, class: "button is-light" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "button is-light" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rezz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice %>
      <div class="notification is-info is-light mb-0">
        <div class="container">
          <%= notice %>
        </div>
      </div>
    <% end %>

    <% if alert %>
      <div class="notification is-danger is-light mb-0">
        <div class="container">
          <%= alert %>
        </div>
      </div>
    <% end %>

    <div class="container">
      <section class="section">
        <%= yield %>
      </section>
    </div>
  </body>
</html>